[2024-06-02T20:47:41.994+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgre_exercises.prediction_result manual__2024-06-02T20:46:28.463729+00:00 [queued]>
[2024-06-02T20:47:41.999+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgre_exercises.prediction_result manual__2024-06-02T20:46:28.463729+00:00 [queued]>
[2024-06-02T20:47:41.999+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 3
[2024-06-02T20:47:42.013+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): prediction_result> on 2024-06-02 20:46:28.463729+00:00
[2024-06-02T20:47:42.017+0000] {standard_task_runner.py:60} INFO - Started process 2256 to run task
[2024-06-02T20:47:42.020+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'postgre_exercises', 'prediction_result', 'manual__2024-06-02T20:46:28.463729+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/create_table.py', '--cfg-path', '/tmp/tmp9ak29dbf']
[2024-06-02T20:47:42.021+0000] {standard_task_runner.py:88} INFO - Job 42: Subtask prediction_result
[2024-06-02T20:47:42.055+0000] {task_command.py:423} INFO - Running <TaskInstance: postgre_exercises.prediction_result manual__2024-06-02T20:46:28.463729+00:00 [running]> on host 35a5c0dbc0eb
[2024-06-02T20:47:42.098+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='msaipulrx@gmail.com' AIRFLOW_CTX_DAG_OWNER='saipul' AIRFLOW_CTX_DAG_ID='postgre_exercises' AIRFLOW_CTX_TASK_ID='prediction_result' AIRFLOW_CTX_EXECUTION_DATE='2024-06-02T20:46:28.463729+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-02T20:46:28.463729+00:00'
[2024-06-02T20:47:42.378+0000] {logging_mixin.py:188} INFO - Table Input
[2024-06-02T20:47:42.406+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/sklearn/base.py:443: UserWarning: X has feature names, but MLPClassifier was fitted without feature names
  warnings.warn(

[2024-06-02T20:47:42.417+0000] {logging_mixin.py:188} INFO - table output
[2024-06-02T20:47:42.423+0000] {logging_mixin.py:188} INFO -       Id  Predicted_Species             executed_timed
0      1                  0 2024-06-02 20:47:41.562233
1      2                  0 2024-06-02 20:47:41.562233
2      3                  0 2024-06-02 20:47:41.562233
3      4                  0 2024-06-02 20:47:41.562233
4      5                  0 2024-06-02 20:47:41.562233
..   ...                ...                        ...
145  146                  2 2024-06-02 20:47:41.562233
146  147                  2 2024-06-02 20:47:41.562233
147  148                  2 2024-06-02 20:47:41.562233
148  149                  2 2024-06-02 20:47:41.562233
149  150                  2 2024-06-02 20:47:41.562233

[150 rows x 3 columns]
[2024-06-02T20:47:42.450+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-06-02T20:47:42.457+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=postgre_exercises, task_id=prediction_result, execution_date=20240602T204628, start_date=20240602T204741, end_date=20240602T204742
[2024-06-02T20:47:42.489+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-06-02T20:47:42.501+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
